config/routes.rb
# frozen_string_literal: true

Spree::Core::Engine.routes.draw do
  root to: 'home#index'

  # devise_for(:spree_user, {
  #   class_name: 'Spree::User',
  #   controllers: {
  #     sessions: 'spree/user_sessions',
  #     registrations: 'spree/user_registrations',
  #     passwords: 'spree/user_passwords',
  #     confirmations: 'spree/user_confirmations'
  #   },
  #   skip: [:unlocks, :omniauth_callbacks],
  #   path_names: { sign_out: 'logout' },
  #   path_prefix: :user,
  #   router_name: :spree
  # })

  resources :users, only: [:edit, :update]

  devise_scope :spree_user do
    get '/login', to: 'user_sessions#new', as: :login
    post '/login', to: 'user_sessions#create', as: :create_new_session
    match '/logout', to: 'user_sessions#destroy', as: :logout, via: Devise.sign_out_via
    get '/signup', to: 'user_registrations#new', as: :signup
    post '/signup', to: 'user_registrations#create', as: :registration
    get '/password/recover', to: 'user_passwords#new', as: :recover_password
    post '/password/recover', to: 'user_passwords#create', as: :reset_password
    get '/password/change', to: 'user_passwords#edit', as: :edit_password
    put '/password/change', to: 'user_passwords#update', as: :update_password
    get '/confirm', to: 'user_confirmations#show', as: :confirmation if Spree::Auth::Config[:confirmable]
  end

  resource :account, controller: 'users'

  resources :products, only: [:index, :show]

  get '/locale/set', to: 'locale#set'
  post '/locale/set', to: 'locale#set', as: :select_locale

  # non-restful checkout stuff
  get '/checkout/registration', to: 'checkout#registration', as: :checkout_registration
  put '/checkout/registration', to: 'checkout#update_registration', as: :update_checkout_registration
  patch '/checkout/update/:state', to: 'checkout#update', as: :update_checkout
  get '/checkout/:state', to: 'checkout#edit', as: :checkout_state
  get '/checkout', to: 'checkout#edit', as: :checkout

  get '/orders/populate', to: 'orders#populate_redirect'
  get '/orders/:id/token/:token' => 'orders#show', as: :token_order

  resources :orders, except: [:index, :new, :create, :destroy] do
    post :populate, on: :collection
    resources :coupon_codes, only: :create
  end

  get '/cart', to: 'orders#edit', as: :cart
  patch '/cart', to: 'orders#update', as: :update_cart
  put '/cart/empty', to: 'orders#empty', as: :empty_cart

  # route globbing for pretty nested taxon and product paths
  get '/t/*id', to: 'taxons#show', as: :nested_taxons

  get '/unauthorized', to: 'home#unauthorized', as: :unauthorized
  get '/cart_link', to: 'store#cart_link', as: :cart_link

  
  namespace :api, format: false, defaults: { format: :json } do
  
    resources :users, only: [] do
      post :request_auth, on: :collection
      post :auth,         on: :collection
      get  :current,      on: :collection
    end
  
    # rozario API
    scope :rozmain do
      get '', to: 'rozmain#index'
      get 'catalog/*permalink', to: 'rozmain#category'
      get 'product/:id', to: 'rozmain#product'
      get 'reviews', to: 'rozmain#reviews'
      # resources :reviews, only: [:index, :create]
    end
  
  end


  namespace :admin do
    resources :reviews
  end
  
end

Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'
end

app/controllers/spree/admin/reviews_controller.rb
module Spree
  module Admin
    class ReviewsController < ResourceController
      


      private

      def collection
        params[:q] ||= {}
        params[:q][:s] ||= "created_at desc"
        @search = super.ransack(params[:q])
        @search.result.page(params[:page]).per(params[:per_page]).order(params[:q][:s])
      end

    end
  end
end

app/views/spree/admin/reviews/_form.html.erb
<div class="row js-reviews-form">
  <div class="col-12">

    <div data-hook="admin_review_form_fields">
      <fieldset class="no-border-top">

        <%= review_form.field_container :text do %>
          <%= review_form.label :text %><br />
          <%= review_form.text_field :text, class: 'fullwidth' %>
        <% end %>

        <%= review_form.field_container :reply do %>
          <%= review_form.label :reply %><br />
          <%= review_form.text_area :reply, class: 'fullwidth' %>
        <% end %>
        
        <%= review_form.field_container :published do %>
          <%= review_form.label :published %><br />
          <%= review_form.check_box :published, { checked: @review.published }, 'true', 'false' %>
        <% end %>

      </fieldset>
    </div>
  </div>

</div>

app/views/spree/admin/reviews/edit.html.erb
<% admin_breadcrumb(t('spree.content')) %>
<% admin_breadcrumb(link_to plural_resource_name(Spree::Review), spree.admin_reviews_path) %>
<% admin_breadcrumb(@review.order.number) %>


<% content_for :page_actions do %>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @review } %>

<%= form_for [:admin, @review] do |review_form| %>
  <%= render partial: 'form', locals: { review_form: review_form } %>
  <div class="clear"></div>
  <%= render partial: 'spree/admin/shared/edit_resource_links' %>
<% end %>

app/views/spree/admin/reviews/index.html.erb
<% admin_breadcrumb(t('spree.content')) %>
<% admin_breadcrumb(plural_resource_name(Spree::Review)) %>

<% content_for :page_actions do %>
  <% if can?(:create, Spree::Review) %>
    <!--<li>
      <%= link_to t('new_review'), new_object_url, id: 'admin_new_review_link', class: 'btn btn-primary' %>
    </li>-->
  <% end %>
<% end %>

<%= paginate @reviews, theme: "solidus_admin" %>

<% if @reviews.any? %>
  <table class="index" id='listing_reviews' data-hook>
    <colgroup>
      <col style="width: 13%" />
      <col style="width: 10%" />
      <col style="width: 10%" />
      <col style="width: 40%" />
      <col style="width: 11%" />
      <col style="width: 8%" />
      <col style="width: 8%" />
    </colgroup>
    <thead>
      <tr data-hook="reviews_header">
        <th><%= sort_link @search, :order_number, Spree::Review.human_attribute_name(:order_number) %></th>
        <th><%= Spree::Review.human_attribute_name(:user_email) %></th>
        <th><%= Spree::Review.human_attribute_name(:rating) %></th>
        <th><%= Spree::Review.human_attribute_name(:text) %></th>
        <th><%= sort_link @search, :created_at, Spree::Review.human_attribute_name(:created_at) %></th>
        <th></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @reviews.each do |review| %>
        <tr id="<%= spree_dom_id review %>" data-hook="reviews_row">
          <td><%= link_to review.order.number, edit_admin_order_path(review.order.number) %></td>
          <td><% if review.user %><%= review.user.email %><% end %></td>
          <td>
            <% review.rating.each_with_index do |r, i| %>
              <span title="<%= Spree::Review.human_attribute_name(r[0]) %>" style="cursor:help"><%= r[1] %></span>
              <% if review.rating.count > i + 1 %>/<% end %>
            <% end if review.rating %>
          </td>
          <td><%= review.text %></td>
          <td><%= review.created_at.to_fs(:short) %></td>
          <td style="font-size:1.35rem;text-align:center;">
            <% unless review.reply.blank? %>
              <i title="Есть ответ" class="fa fa-check-circle" style="color:var(--green)"></i>
            <% else %>
              <i title="Нет ответа" class="fa fa-minus-circle" style="color:var(--red)"></i>
            <% end %>
            <% if review.published %>
              <i title="Опубликован" class="fa fa-eye" style="color:var(--green)"></i>
            <% else %>
              <i title="Не опубликован" class="fa fa-eye-slash" style="color:var(--red)"></i>
            <% end %>
          </td>
          
          <td class="actions">
            <% if can?(:update, review) %>
              <%= link_to_edit review, no_text: true %>
            <% end %>
            <% if can?(:destroy, review) %>
              <%= link_to_delete review, no_text: true %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                 resource: Spree::Review,
                 new_resource_url: new_object_url %>
  </div>
<% end %>

<%= paginate @reviews, theme: "solidus_admin" %>

app/views/spree/admin/reviews/new.html.erb
<% admin_breadcrumb(t('spree.content')) %>
<% admin_breadcrumb(link_to plural_resource_name(Spree::Review), spree.admin_reviews_path) %>
<% admin_breadcrumb(t('new_review')) %>


<% content_for :page_actions do %>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @review } %>

<%= form_for [:admin, @review] do |review_form| %>
  <%= render partial: 'form', locals: { review_form: review_form } %>

  <div class="clear"></div>

  <%= render partial: 'spree/admin/shared/new_resource_links' %>
<% end %>